//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXfromDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CustomerData
    {
        public int customer_id { get; set; }
        public string first_name { get; set; }
        public string email { get; set; }
    }
}
